#cloud-config
packages:
  - nginx

runcmd:
 - sudo systemctl enable nginx
 - rm -f /var/www/html/*
 - ["bash", "-c", "echo \"<h1>nginx: $(hostname)</h1>\" > /var/www/html/index.html"]
 - chmod 755 /var/www/html/index.html